---
# creating directory for virtual
  - name: new directory for virtual env
    file:
      path: "{{ deployment_path }}"
      state: directory
      mode: '0755'

# create a virtual environment
  - name: create a virtual environment
    pip:
      name: virtualenv
      virtualenv: "{{ deployment_path }}"
      state: present

# starting the virtual environment
  - name: activate the virtual environment
    shell: source "{{ deployment_path }}"/bin/activate

 
      
